#!/bin/bash -u

APPNAME=musicdashboardtutorial
VERSION=1.0.0
PACKAGE=$APPNAME-$VERSION.tar.gz
BUILDDIR=build
SPLUNK_USER=admin
SPLUNK_PASS=changeme

read -r -d '' helptext <<- EOF
Automation control for docker compose
Usage:
  $0 <command> [<command> ...]

Valid commands:
  help  - shows this message
  start - start containers
  build - build software
  test  - install and run software
  clean - cleans up environment
  
Splunk container shortcuts:
  splunk-shell - interactive shell

Python2 container shortcuts:
  python2-shell - interactive BASH shell
  python2       - interactive python prompt
EOF

function start() {
  docker-compose down
  docker-compose up -d
}

function build() {
  slim="docker-compose run python2 slim"
  $slim validate $APPNAME
  $slim describe $APPNAME
  $slim package $APPNAME
}

function test() {
  splunk="docker-compose exec splunk /opt/splunk/bin/splunk"
  $splunk login -auth $SPLUNK_USER:$SPLUNK_PASS
  $splunk remove app $APPNAME || true
  $splunk install app $PACKAGE
  docker-compose exec splunk cp -rf test/local /opt/splunk/etc/apps/$APPNAME
  $splunk restart
}

function clean() {
  docker-compose down
  rm -rf $BUILDDIR $PACKAGE
}

function splunk-shell() {
  docker-compose exec splunk bash
}

function python2() {
  docker-compose run python2
}

function python2-shell() {
  docker-compose run python2 bash
}

function help() {
  echo "$helptext"
  exit 1
}

# run commands
if [[ $# = 0 ]]; then help; fi
for command in $@; do
  case $command in 
	start) start;;
	build) build;;
	test) test;;
	clean) clean;;
	splunk) splunk;;
	splunk-shell) splunk-shell;;
	python2) python2;;
	python2-shell) python2-shell;;
	*) help;;
  esac
done
