#!/bin/bash -u

APPNAME=musicdashboardtutorial
VERSION=1.0.0
TARGET=$APPNAME-$VERSION
PACKAGE=$APPNAME-$VERSION.spl
BUILDDIR=build
SPLUNK_USER=admin
SPLUNK_PASS=changeme

read -r -d '' helptext <<- EOF
Automation control for docker compose
Usage:
  $0 <command> [<command> ...]

Valid commands:
  help - shows this message
  start - start containers
  build - build software
  test - install and run software
  splunk - interactive splunk shell
  clean - cleans up environment
EOF

function start_cmd() {
  docker-compose down
  docker-compose up -d
}

function build_cmd() {
  rm -rf $BUILDDIR 
  mkdir -p $BUILDDIR
  cp -r $APPNAME $BUILDDIR
  pushd $BUILDDIR 
  tar czf $PACKAGE $APPNAME
  cp -f $PACKAGE ..
  popd
}

function test_cmd() {
  splunk="docker-compose exec splunk /opt/splunk/bin/splunk"
  $splunk login -auth $SPLUNK_USER:$SPLUNK_PASS
  $splunk remove app $APPNAME || true
  $splunk install app $PACKAGE
  docker-compose exec splunk cp -rf test/local /opt/splunk/etc/apps/$APPNAME
  $splunk restart
}

function clean_cmd() {
  docker-compose down
  rm -rf $BUILDDIR $PACKAGE
}

function splunk_cmd() {
  docker-compose exec splunk bash
}

function help_cmd() {
  echo "$helptext"
  exit 1
}

# run commands
if [[ $# = 0 ]]; then help_cmd; fi
for command in $@; do
  case $command in 
	start) start_cmd;;
	build) build_cmd;;
	test) test_cmd;;
	clean) clean_cmd;;
	splunk) splunk_cmd;;
	*) help_cmd;;
  esac
done
