#!/bin/bash -u

APPNAME=musicdashboardtutorial
VERSION=1.0.0
TARGET=$APPNAME-$VERSION
PACKAGE=$APPNAME-$VERSION.spl
BUILDDIR=build
SPLUNK_USER=admin
SPLUNK_PASS=changeme

read -r -d '' helptext <<- EOF
Project automation development script
Usage:
  $0 <command> [<command> ...]

Valid commands:
  help - shows this message
  start - start containers
  build - build software
  test - install and run software
  splunk - interactive splunk shell
  clean - cleans up environment
EOF

function start_cmd() {
  docker-compose down
  docker-compose up -d
}

function build_cmd() {
  rm -rf $BUILDDIR 
  mkdir -p $BUILDDIR
  cp -r $APPNAME $BUILDDIR
  pushd $BUILDDIR 
  tar czf $PACKAGE $APPNAME
  cp -f $PACKAGE ..
  popd
}

function test_cmd() {
  splunk="docker-compose exec splunk splunk"
  $splunk login -auth $SPLUNK_USER:$SPLUNK_PASS 
  $splunk remove app $APPNAME || true
  $splunk install app $PACKAGE
}

function clean_cmd() {
  docker-compose down
  rm -rf $BUILDDIR $PACKAGE
}

function splunk_cmd() {
  docker-compose exec splunk bash
}

function help() {
  echo "$helptext"
  exit 1
}

function main() {
  if [[ $# = 0 ]]; then help; fi
  valid_commands="$(declare -F -p | cut -d " " -f 3 | grep '\w\+_cmd' | awk 1 ORS='\\|')help"
  for command in $@; do
    if (echo "${command}_cmd" | grep "$valid_commands" > /dev/null); then set -e; ${command}_cmd; else help; fi
  done
}

main "$@"
